//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace consultasDietas.wsDieta {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsDietaSoap", Namespace="http://tempuri.org/")]
    public partial class wsDieta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback buscarDietaPorClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarDietaPorRangoFechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback mostrarDietasPorClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback mostrarDetallePorDietaOperationCompleted;
        
        private System.Threading.SendOrPostCallback mostrarDetallePorClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback contarClientePorSexoOperationCompleted;
        
        private System.Threading.SendOrPostCallback mostrarClientePorSexoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsDieta() {
            this.Url = global::consultasDietas.Properties.Settings.Default.consultasDietas_wsDieta_wsDieta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event buscarDietaPorClienteCompletedEventHandler buscarDietaPorClienteCompleted;
        
        /// <remarks/>
        public event buscarDietaPorRangoFechaCompletedEventHandler buscarDietaPorRangoFechaCompleted;
        
        /// <remarks/>
        public event mostrarDietasPorClienteCompletedEventHandler mostrarDietasPorClienteCompleted;
        
        /// <remarks/>
        public event mostrarDetallePorDietaCompletedEventHandler mostrarDetallePorDietaCompleted;
        
        /// <remarks/>
        public event mostrarDetallePorClienteCompletedEventHandler mostrarDetallePorClienteCompleted;
        
        /// <remarks/>
        public event contarClientePorSexoCompletedEventHandler contarClientePorSexoCompleted;
        
        /// <remarks/>
        public event mostrarClientePorSexoCompletedEventHandler mostrarClientePorSexoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarDietaPorCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarDietaPorCliente(string nom) {
            object[] results = this.Invoke("buscarDietaPorCliente", new object[] {
                        nom});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarDietaPorClienteAsync(string nom) {
            this.buscarDietaPorClienteAsync(nom, null);
        }
        
        /// <remarks/>
        public void buscarDietaPorClienteAsync(string nom, object userState) {
            if ((this.buscarDietaPorClienteOperationCompleted == null)) {
                this.buscarDietaPorClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarDietaPorClienteOperationCompleted);
            }
            this.InvokeAsync("buscarDietaPorCliente", new object[] {
                        nom}, this.buscarDietaPorClienteOperationCompleted, userState);
        }
        
        private void OnbuscarDietaPorClienteOperationCompleted(object arg) {
            if ((this.buscarDietaPorClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarDietaPorClienteCompleted(this, new buscarDietaPorClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/buscarDietaPorRangoFecha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscarDietaPorRangoFecha(string fecha1, string fecha2) {
            object[] results = this.Invoke("buscarDietaPorRangoFecha", new object[] {
                        fecha1,
                        fecha2});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscarDietaPorRangoFechaAsync(string fecha1, string fecha2) {
            this.buscarDietaPorRangoFechaAsync(fecha1, fecha2, null);
        }
        
        /// <remarks/>
        public void buscarDietaPorRangoFechaAsync(string fecha1, string fecha2, object userState) {
            if ((this.buscarDietaPorRangoFechaOperationCompleted == null)) {
                this.buscarDietaPorRangoFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarDietaPorRangoFechaOperationCompleted);
            }
            this.InvokeAsync("buscarDietaPorRangoFecha", new object[] {
                        fecha1,
                        fecha2}, this.buscarDietaPorRangoFechaOperationCompleted, userState);
        }
        
        private void OnbuscarDietaPorRangoFechaOperationCompleted(object arg) {
            if ((this.buscarDietaPorRangoFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarDietaPorRangoFechaCompleted(this, new buscarDietaPorRangoFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mostrarDietasPorCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mostrarDietasPorCliente(string client) {
            object[] results = this.Invoke("mostrarDietasPorCliente", new object[] {
                        client});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void mostrarDietasPorClienteAsync(string client) {
            this.mostrarDietasPorClienteAsync(client, null);
        }
        
        /// <remarks/>
        public void mostrarDietasPorClienteAsync(string client, object userState) {
            if ((this.mostrarDietasPorClienteOperationCompleted == null)) {
                this.mostrarDietasPorClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmostrarDietasPorClienteOperationCompleted);
            }
            this.InvokeAsync("mostrarDietasPorCliente", new object[] {
                        client}, this.mostrarDietasPorClienteOperationCompleted, userState);
        }
        
        private void OnmostrarDietasPorClienteOperationCompleted(object arg) {
            if ((this.mostrarDietasPorClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mostrarDietasPorClienteCompleted(this, new mostrarDietasPorClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mostrarDetallePorDieta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mostrarDetallePorDieta(string diet) {
            object[] results = this.Invoke("mostrarDetallePorDieta", new object[] {
                        diet});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void mostrarDetallePorDietaAsync(string diet) {
            this.mostrarDetallePorDietaAsync(diet, null);
        }
        
        /// <remarks/>
        public void mostrarDetallePorDietaAsync(string diet, object userState) {
            if ((this.mostrarDetallePorDietaOperationCompleted == null)) {
                this.mostrarDetallePorDietaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmostrarDetallePorDietaOperationCompleted);
            }
            this.InvokeAsync("mostrarDetallePorDieta", new object[] {
                        diet}, this.mostrarDetallePorDietaOperationCompleted, userState);
        }
        
        private void OnmostrarDetallePorDietaOperationCompleted(object arg) {
            if ((this.mostrarDetallePorDietaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mostrarDetallePorDietaCompleted(this, new mostrarDetallePorDietaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mostrarDetallePorCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mostrarDetallePorCliente(string client) {
            object[] results = this.Invoke("mostrarDetallePorCliente", new object[] {
                        client});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void mostrarDetallePorClienteAsync(string client) {
            this.mostrarDetallePorClienteAsync(client, null);
        }
        
        /// <remarks/>
        public void mostrarDetallePorClienteAsync(string client, object userState) {
            if ((this.mostrarDetallePorClienteOperationCompleted == null)) {
                this.mostrarDetallePorClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmostrarDetallePorClienteOperationCompleted);
            }
            this.InvokeAsync("mostrarDetallePorCliente", new object[] {
                        client}, this.mostrarDetallePorClienteOperationCompleted, userState);
        }
        
        private void OnmostrarDetallePorClienteOperationCompleted(object arg) {
            if ((this.mostrarDetallePorClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mostrarDetallePorClienteCompleted(this, new mostrarDetallePorClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/contarClientePorSexo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet contarClientePorSexo(string sex) {
            object[] results = this.Invoke("contarClientePorSexo", new object[] {
                        sex});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void contarClientePorSexoAsync(string sex) {
            this.contarClientePorSexoAsync(sex, null);
        }
        
        /// <remarks/>
        public void contarClientePorSexoAsync(string sex, object userState) {
            if ((this.contarClientePorSexoOperationCompleted == null)) {
                this.contarClientePorSexoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncontarClientePorSexoOperationCompleted);
            }
            this.InvokeAsync("contarClientePorSexo", new object[] {
                        sex}, this.contarClientePorSexoOperationCompleted, userState);
        }
        
        private void OncontarClientePorSexoOperationCompleted(object arg) {
            if ((this.contarClientePorSexoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.contarClientePorSexoCompleted(this, new contarClientePorSexoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/mostrarClientePorSexo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet mostrarClientePorSexo(string sex) {
            object[] results = this.Invoke("mostrarClientePorSexo", new object[] {
                        sex});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void mostrarClientePorSexoAsync(string sex) {
            this.mostrarClientePorSexoAsync(sex, null);
        }
        
        /// <remarks/>
        public void mostrarClientePorSexoAsync(string sex, object userState) {
            if ((this.mostrarClientePorSexoOperationCompleted == null)) {
                this.mostrarClientePorSexoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmostrarClientePorSexoOperationCompleted);
            }
            this.InvokeAsync("mostrarClientePorSexo", new object[] {
                        sex}, this.mostrarClientePorSexoOperationCompleted, userState);
        }
        
        private void OnmostrarClientePorSexoOperationCompleted(object arg) {
            if ((this.mostrarClientePorSexoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mostrarClientePorSexoCompleted(this, new mostrarClientePorSexoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarDietaPorClienteCompletedEventHandler(object sender, buscarDietaPorClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarDietaPorClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarDietaPorClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void buscarDietaPorRangoFechaCompletedEventHandler(object sender, buscarDietaPorRangoFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarDietaPorRangoFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarDietaPorRangoFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void mostrarDietasPorClienteCompletedEventHandler(object sender, mostrarDietasPorClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mostrarDietasPorClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mostrarDietasPorClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void mostrarDetallePorDietaCompletedEventHandler(object sender, mostrarDetallePorDietaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mostrarDetallePorDietaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mostrarDetallePorDietaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void mostrarDetallePorClienteCompletedEventHandler(object sender, mostrarDetallePorClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mostrarDetallePorClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mostrarDetallePorClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void contarClientePorSexoCompletedEventHandler(object sender, contarClientePorSexoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class contarClientePorSexoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal contarClientePorSexoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void mostrarClientePorSexoCompletedEventHandler(object sender, mostrarClientePorSexoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mostrarClientePorSexoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mostrarClientePorSexoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591